HelpDeskManagement/Models/HelpDeskDBContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HelpDeskManagement.Models
{
    public partial class HelpDeskDBContext : DbContext
    {
        public HelpDeskDBContext()
        {
        }

        public HelpDeskDBContext(DbContextOptions<HelpDeskDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<UserMst> UserMsts { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
//            if (!optionsBuilder.IsConfigured)
//            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//                optionsBuilder.UseSqlServer("Server=LAPTOP-L986OD5L\\SQLEXPRESS01;Database=HelpDeskDB;Trusted_Connection=true;");
//            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserMst>(entity =>
            {
                entity.ToTable("UserMst");

                entity.Property(e => e.Address).HasMaxLength(255);

                entity.Property(e => e.Contact).HasMaxLength(255);

                entity.Property(e => e.Email).HasMaxLength(255);

                entity.Property(e => e.HintAns).HasMaxLength(255);

                entity.Property(e => e.HintQue).HasMaxLength(255);

                entity.Property(e => e.Passwrod).HasMaxLength(255);

                entity.Property(e => e.UserName).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

HelpDeskManagement/Models/UserMst.cs
using System;
using System.Collections.Generic;

namespace HelpDeskManagement.Models
{
    public partial class UserMst
    {
        public int Id { get; set; }
        public string UserName { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string? Address { get; set; }
        public string? Contact { get; set; }
        public string? Passwrod { get; set; }
        public string? HintQue { get; set; }
        public string? HintAns { get; set; }
        public int UserTypeId { get; set; }
    }
}

HelpDeskManagement/Controllers/LoginController.cs
using HelpDeskManagement.Models;
using HelpDeskManagement.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace HelpDeskManagement.Controllers
{
    public class LoginController : Controller
    {

        private readonly HelpDeskDBContext _context;

        public LoginController(HelpDeskDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        //[HttpPost]

        //public async Task<ActionResult<UserMst>> validateUser([FromBody] UserMst obj)
        //{
        //    Response res = new Response();
        //    var user = await _context.UserMsts.FindAsync(obj.Email);
        //    if (user == null)
        //    {
        //        return BadRequest("user not exist");
        //    }

        //    if (user.Passwrod != obj.Passwrod)
        //    {
        //        return BadRequest("Password is wrong");
        //    }

        //    return Ok("you are logged in");
        //}

        [HttpPost]

        public ActionResult validateUser([FromBody] UserMst obj)
        {
            Response res = new Response();
            //var user = _context.UserMsts.Find(obj.Email);
            var user = _context.UserMsts.SingleOrDefault(a => a.Email == obj.Email);
            if (user == null)
            {
                res.status = false;
                res.message = "user not found";
                return Ok(res);
            }

            if (user.Passwrod != obj.Passwrod)
            {
                res.status = false;
                res.message = "password in wrong";
                return Ok(res);
            }

            res.status = true;
            res.message = "success";
            return Ok(res);
        }
    }
}

HelpDeskManagement/Controllers/UserController.cs
using HelpDeskManagement.Models;
using HelpDeskManagement.ViewModel;
using Microsoft.AspNetCore.Mvc;


namespace HelpDeskManagement.Controllers
{
    public class UserController : Controller
    {
        private readonly HelpDeskDBContext _context;

        public UserController(HelpDeskDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        
        public IActionResult saveUser([FromBody]UserMst model)
        {
                Response res = new Response();
                _context.UserMsts.Add(model);
                _context.SaveChanges();
                res.status = true;
                res.message = "success";
                return Ok(res);
            
            
        }

        [HttpPost]

        public async Task<ActionResult<UserMst>> validateUser([FromBody]UserMst obj)
        {
            Response res = new Response();
            var user = await _context.UserMsts.FindAsync(obj.Email);
            if(user == null)
            {
                return BadRequest("user not exist");
            }

            if(user.Passwrod != obj.Passwrod)
            {
                return BadRequest("Password is wrong");
            }

            return Ok("you are logged in");
        }



    }
}

HelpDeskManagement/Views/Login/Index.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>Log in Here </title>
        <link rel="stylesheet" href="~/css/Login/Index.css" asp-append-version="true" />
    </head>
    <body>
     @* <form method="post" >
        <fieldset>
          <legend>Add Customer</legend>
          <div>
            <label for="Email">Email : </label>
            <input type="email" name="Email" value="" id="EmailInput" />
          </div>
          <div>
            <label for="Password">Password:</label>
            <input type="password" name="Password" value="" id="PasswordInput" />
          </div>
          <div>
            <label>&nbsp;</label>
            <input type="submit" value="Submit" class="submit" id="btnSave" />
          </div>
        </fieldset>
      </form>*@

      <div id="tsparticles"></div>
<div class="login-box">
  <h2>Login</h2>
  <form>
    <div class="user-box">
      <input type="email" name="Email" value="" id="EmailInput" />
      <label>Username</label>
    </div>
    <div class="user-box">
      <input type="password" name="Password" value="" id="PasswordInput" />
      <label>Password</label>
    </div>
    <a sp-area="" asp-controller="User" asp-action="Index"  id="btnRegister">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Create new
    </a>
    <a href="#"  type="submit" value="Submit" class="submit" id="btnSave">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Login
    </a>
    
  </form>
</div>

      <script src="~/lib/jquery/dist/jquery.min.js"></script>
       <script>
       
    $(document).ready(function () {
       
        $("#btnSave").click(function (e) {

            e.preventDefault();
            var user;
            user = {
                "Email": $("#EmailInput").val(),
                "Passwrod": $("#PasswordInput").val()
            }

            console.log(JSON.stringify(user));
            
            debugger

            $.ajax({
                url: "/Login/validateUser",
                type: "POST",
                data: JSON.stringify(user),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (response) {
                    
                    console.log(response);
                    alert(response.message);
                },
                error: function (er) {
                    //Toast.fire({ icon: 'error', title: "Error Occured!, please check logs" });
                    console.log(er);

                    
                }
            });

        });



    });





    </script>

    </body>
</html>

HelpDeskManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpDeskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelpDeskManagement.styles.css" asp-append-version="true" />
</head>
<body>
   @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">HelpDeskManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HelpDeskManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HelpDeskManagement/Views/User/Index.cshtml
<!DOCTYPE html>
<html>
<head>

    <title>Register Here </title>
    <link rel="stylesheet" href="~/css/User/Index.css" asp-append-version="true"/>
</head>
<body>
    @*<form method="post" id="form">
        <fieldset>
            <legend>Add Customer</legend>
            <div>
                <label for="UserName">Name:</label>
                <input type="text" name="UserName" value="" id="UserNameInput" />
            </div>
            <div>
                <label for="Email">Email : </label>
                <input type="email" name="Email" value="" id="EmailInput" />
            </div>
            <div>
                <label for="Address">Address:</label>
                <input type="text" name="Address" value="" id="AddressInput" />
            </div>
            <div>
                <label for="Contact">Contact:</label>
                <input type="number" name="Contact" value="" id="ContactInput" />
            </div>
            <div>
                <label for="Password">Password:</label>
                <input type="password" name="Password" value="" id="PasswordInput" />
            </div>
            <div>
                <label for="HintQue">Hint Question :</label>
                <input type="text" name="HintQue" value="" id="HintQueInput" />
            </div>
            <div>
                <label for="HintAns">Hint Answer :</label>
                <input type="text" name="HintAns" value="" id="HintAnsInput" />
            </div>
            <div>
                <label for="Type">Choose a User type :</label>
                <select name="Type" id="TypeInput">
                    <option value="Admin">Admin</option>
                    <option value="EMmployee">Employee</option>
                </select>
            </div>
            <div>
                <label>&nbsp;</label>
                <input type="button" id="btnSave" value="Submit" class="submit" onsubmit="submitHandle" />
            </div>
        </fieldset>
    </form>*@


    <div class="container">
  @*<div class="row"><img src="https://iephosting.com/app/views/client/bootstrap/images/graphic8.svg" id="imageAsBackground" alt="" /></div>*@
  <div class="row align-items-center justify-content-center" style="height:100vh;">
    <div class="col-sm-12 col-md-8 col-lg-6 col-xl-4">
      <div class="card">
        <div class="card-body">
          <d@*iv class="form-icon">
            <div class="icon-holder">
              <i class="fa-2x fa-solid fa-user-plus text-light" style="margin-top: 5px;"></i>
            </div>
          </div>*@
          <h3 class="text-center">REGISTER</h3>
          <form id="registerForm">
            <div class="form-floating mb-2">
              
              <input type="text" name="UserName" value="" id="UserNameInput" class="form-control" autocomplete="off"/>
              <label for="userInput">Username</label>
            </div>
            <div class="form-floating mb-2">
              
              <input type="email" name="Email" value="" id="EmailInput"  class="form-control" autocomplete="off"/>
              <label for="emailInput">Email address</label>
            </div>
            <div class="form-floating mb-2">
              <input type="password" name="Password" value="" id="PasswordInput" class="form-control" />
              <label for="passwordInput">Password</label>
            </div>
            <div class="form-floating mb-2">
              <input type="text" name="Address" value="" id="AddressInput" class="form-control" />
              <label for="Address">Address</label>
            </div>
            <div class="form-floating mb-2">
              <input type="number" name="Contact" value="" id="ContactInput" class="form-control" autocomplete="off" />
              <label for="Contact">Contact No</label>
            </div>
            <div class="form-floating mb-2">
              <input  type="text" name="HintQue" value="" id="HintQueInput" class="form-control" />
              <label for="HintQue">Hint Question</label>
            </div>
            <div class="form-floating mb-2">
              <input type="text" name="HintAns" value="" id="HintAnsInput" class="form-control" />
              <label for="HintAns">Hint Answer</label>
            </div>
            <div class="form-floating mb-2">
                <label for="Type">Choose a User type :</label>
                <select name="Type" id="TypeInput">
                    <option value="Admin">Admin</option>
                    <option value="EMmployee">Employee</option>
                </select>
            </div>

            <div class="text-center mb-5">
              <button class="btn btn-outline-primary" type="submit">REGISTER</button>
            </div>
          </form>
        </div>
        @*<div class="card-footer text-center">
          <button class="btn btn-sm btn-primary radius" data-bs-toggle="modal" data-bs-target="#staticBackdrop">See List of Accounts</button>
        </div>*@
      </div>
    </div>
  </div>
</div>
@*
<div class="modal" id="staticBackdrop">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">List of registered accounts</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">

        <div class="table-responsive">
          <table id="accountTable" class="table table-striped" style="width:100%">
            <thead>
              <tr>
                <th>#</th>
                <th>Email</th>
                <th>Username</th>
                <th>Name</th>
                <th>Password</th>
              </tr>
            </thead>
            <tbody id="tbody">
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>*@


     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
       
    $(document).ready(function () {

        $("#btnSave").click(function () {

            var user;
            user = {
                "UserName": $("#UserNameInput").val(),
                "Email": $("#EmailInput").val(),
                "Address": $("#AddressInput").val(),
                "Contact": $("#ContactInput").val(),
                "Passwrod": $("#PasswordInput").val(),
                "HintQue": $("#HintQueInput").val(),
                "HintAns": $("#HintAnsInput").val(),
                "UserTypeId": 1
            }

            console.log(JSON.stringify(user));
            
            debugger

            $.ajax({
                url: "/User/saveUser",
                type: "POST",
                data: JSON.stringify(user),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (response) {
                    console.log(response);
                    
                },
                error: function (er) {
                    //Toast.fire({ icon: 'error', title: "Error Occured!, please check logs" });
                    console.log(er);

                    
                }
            });

        });



    });





    </script>
   
   @* @section Scripts {

    <script src="~/Areas/Registration/Scripts/Organisation/Index.js?_=@DateTime.Now.Ticks"></script>
}*@
</body>




</html>